# Generated by Django 4.2.3 on 2023-07-19 16:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('tablets', 'Tablets'), ('televisions', 'Televisions'), ('headphones', 'Headphones'), ('cameras', 'Cameras'), ('gaming', 'Gaming'), ('smart_home', 'Smart Home'), ('wearables', 'Wearables'), ('accessories', 'Accessories'), ('sports', 'Sports'), ('bikes', 'Bikes'), ('motorcycles', 'Motorcycles')], max_length=100)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
